#!/bin/bash
apex_domains=(
richlandcountysc.gov
lex-co.sc.gov
spartanburgcounty.org
greenvillecounty.org
charlestoncounty.org
horrycounty.org
dorchestercountysc.gov
berkeleycountysc.gov
colletoncounty.org
clarendoncountygov.org
beaufortcountysc.gov
orangeburgcounty.org
williamsburgcounty.sc.gov
co.pickens.sc.us
oconeesc.com
newberrycounty.net
saludacounty.sc.gov
edgefieldcounty.sc.gov
bambergcountysc.gov
autaugaco.org
elmoreco.org
chiltoncounty.org
etowahcounty.org
coosacountyal.com
co.escambia.al.us
lowndescountycommission-al.com
blountcountyal.gov
stclairco.com
alabamagis.comConecuh
dekalbcountyal.us
cleburnecounty.us
tallaco.com
talladegacountyal.org
sumtercountyal.com
crenshawcountyalonline.comdefault?pageID=1#
bibbal.com
baldwincountyal.govhome
co.cullman.al.us
pickenscountyal.com
dallascounty-al.orgdefault?pageID=2
monroecountyonline.com
marengocountyal.com
madisoncountyal.gov
mc-ala.org
jccal.org
lauderdalecountyal.gov
Choctaw - NA
mobilecountyal.gov
co.morgan.al.us
marshallco.org
shelbyal.com
alabamagis.comBarbour
leeco.us
pike
colbertcounty.org
fayetteal.org
tuscco.com
calhouncounty.org
limestonecounty-al.gov
jacksoncountyal.gov
covcounty.com
houstoncounty.org
butler
cherokeecounty-al.gov
franklincountyal.org
chamberscountyal.gov
henrycountyal.com
marion
bullock
maconcountyal.com
maricopa.gov
webcms.pima.gov
coconino.az.gov
pinalcountyaz.govPagesHome
yavapai.us
cochise.az.gov
mohavecounty.us
gilacountyaz.gov
yumacountyaz.gov
co.greenlee.az.us
http:co.la-paz.az.us
graham.az.gov
apachecountyaz.gov
navajocountyaz.gov
santacruzcountyaz.gov
arkansas county
pulaskicounty.net
craigheadcounty.org
washingtoncountyar.gov
poinsettcounty.us
lonoke
deshacounty.arkansas.gov
chicotcounty.arkansas.gov
cleburnecountyar.com
prairiecounty.arkansas.gov
faulknercounty.org
crittenden.ark.org
bentoncountyar.gov
salinecounty.org
garlandcounty.org
yellcounty.net
hempstead
popecountyar.gov
baxtercounty.org
little river county
sevier
boonecountyar.com
stfranciscountyar.org
izardcountyar.org
crosscountyar.org
whitecountyar.org
conwaycountyar.com
ouachita county
jackson county
jeffersoncountyar.gov
searcy county
polk county
sebastiancountyar.gov
millercountyar.com
hotspringcounty.arkansas.gov
ashley county
van buren
mississippicountyar.org
clarkcountyarkansas.com
leecounty.arkansas.gov
lincolncounty.arkansas.gov
lawrencecountyarkansas.com
sharpcounty.arkansas.gov
co.carroll.ar.us
marioncounty.arkansas.gov
bradley county
phillipscounty.arkansas.gov
monroecounty.arkansas.gov
dallas county
randolph county
calhouncounty.arkansas.gov
lacounty.gov
contracosta.ca.gov
stancounty.com
sccgov.org
solanocounty.com
sjgov.org
marincounty.org
ocgov.com
placer.ca.gov
acgov.org
sbcounty.gov
yuba.org
yolocounty.org
buttecounty.net
kerncounty.com
co.merced.ca.us
smcgov.org
co.fresno.ca.us
saccounty.net
humboldtgov.org
sf.gov
sandiegocounty.gov
lassen county 
calaverasgov.us
ventura.org
co.shasta.ca.usindex
countyofnapa.org
rivco.org
slocounty.ca.gov
cosb.us
tularecounty.ca.gov
amadorgov.org
co.modoc.ca.us
tuolumnecounty.ca.gov
sonomacounty.ca.gov
co.siskiyou.ca.us
co.santa-cruz.ca.us
imperialcounty.org
mariposacounty.org
maderacounty.com
co.tehama.ca.us
co.del-norte.ca.us
co.monterey.ca.us
plumascounty.us
inyocounty.us
suttercounty.org
countyofkings.com
countyofsb.org
countyofcolusa.org
edcgov.us
mendocinocounty.org
arapahoegov.com
elpasoco.com
broomfield.org
weldgov.com
larimer.org
denvergov.org
douglas.co.us
adcogov.org
bouldercounty.org
co.routt.co.us
prowerscounty.net
jeffco.us
oterogov.com
co.laplata.co.us
rbc.us
pitkincounty.com
moffatcounty.colorado.gov
chaffeecounty.org
gunnisoncounty.org
custer county
eaglecounty.us
huerfano.us
co.teller.co.us
gilpincounty.org
colorado.gov
mesacounty.us
summitcountyco.gov
elbertcounty-co.gov
clearcreekcounty.us
hinsdalecounty.colorado.gov
yumacounty.net
montezumacounty.org
kitcarsoncounty.colorado.gov
lasanimascounty.colorado.gov
montrosecounty.net
alamosacounty.colorado.gov
bacacountyco.gov
conejoscounty.org
saguachecounty.net
archuletacounty.org
ouraycountyco.gov
sedgwickcounty.colorado.gov
parkco.us
co.grand.co.us
logancounty.colorado.gov
fremontco.com
kiowacounty-colorado.com
garfield-county.com
county.pueblo.org
dolorescounty.org
deltacounty.com
portal.ct.gov
litchfieldcty.com
portal.ct.gov
portal.ct.gov
portal.ct.gov
portal.ct.gov
portal.ct.gov
portal.ct.gov
nccde.org
co.kent.de.us
sussexcountyde.gov
broward.org
miamidade.gov
pinellascounty.org
brevardfl.gov
hillsboroughcounty.org
palm beach
polk-county.net
duval couunty
osceola.org
mywakulla.com
volusia.org
co.okaloosa.fl.us
nassaucountyfl.com
co.okeechobee.fl.us
pascocountyfl.net
ircgov.com
alachuacounty.us
hendryfla.net
stlucieco.gov
claycountygov.com
co.st-johns.fl.us
myglades.com
flaglercounty.org
sumtercountyfl.gov
myescambia.com
santarosa.fl.gov
co.walton.fl.us
orangecountyfl.net
mymanatee.org
hernandocounty.us
suwcounty.org
hardeecounty.net
columbiacountyfla.com
gadsdencountyfl.gov
desotobocc.com
scgov.net
gilchrist.fl.us
lakecountyfl.gov
washingtonfl.com
monroecounty-fl.gov
citrusbocc.com
marioncountyfl.org
co.bay.fl.us
charlottecountyfl.gov
leegov.com
cms.leoncountyfl.gov
highlandsfl.gov
seminolecountyfl.gov
lafayettecountyfl.org
martin.fl.us
gwinnettcounty.com
dekalbcountyga.gov
forsythco.com
coweta.ga.us
hallcounty.org
fayettecountyga.gov
rockdalecountyga.gov
bartowga.org
cobbcounty.org
maconbibb.us
paulding.gov
glynncounty.org
habershamga.com
twiggscounty.us
rabuncounty.ga.gov
bullochcounty.net
lowndescounty.com
chattoogacounty.org
cherokeega.com
toombscountyga.gov
bleckley.org
tattnallcountyga.com
effinghamcounty.org
catoosa.com
meriwethercountyga.gov
fannincountyga.com
pickenscountyga.gov
doolycountyga.com
berriencountygeorgia.com
fultoncountyga.gov
tiftcounty.org
haralsoncountyga.gov
metter-candlercounty.com
schleycountyga.us
clinchcountyga.gov
benhillcounty-ga.gov
upsoncountyga.org
treutlencountyga.com
jacksoncountygov.com
glynncounty.org
screvencountyboc.com
glascockcountyga.com
townscountyga.org
troupcountyga.gov
hawkinsville-pulaski.org
echolscountyga.com
sumtercountyga.us
lanier counmty
dadecounty-ga.gov
oglethorpecountyga.gov
elbertga.us
hawaiicounty.gov
mauicounty.gov
kauai.gov
honolulu.gov
kalawoa
idahocounty.org
kcgov.us
adacounty.id.gov
co.fremont.id.us
co.bonneville.id.us
elmorecounty.org
owyheecounty.net
latah.id.us
shoshonecounty.id.gov
co.custer.id.us
co.nezperce.id.us
idaho.gov
lemhicountyidaho.org
tetoncountyidaho.gov
goodingcounty.org
idaho.gov
bannockcounty.us
twinfallscounty.org
oneidacountyid.com
cariboucounty.us
jeromecountyid.us
boisecounty.us
co.blaine.id.us
canyonco.org
bearlakecounty.info
minidoka.id.us
co.valley.id.us
bonnercountyid.gov
payettecounty.org
co.madison.id.us
lincolncountyid.us
co.jefferson.id.us
clark-co.id.gov
co.bingham.id.us
boundarycountyid.org
co.power.id.us
clearwatercounty.org
lewiscountyid.us
gemcounty.org
cassiacounty.org
co.washington.id.us
idaho.gov
co.adams.id.us
franklincountyidaho.org
)
curl_command=`
`"curl -svo /dev/null "`
    `"-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) "`
        `"AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36' "`
    `"-H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif"`
        `",image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' "`
    `"-H 'accept-language: en-US,en;q=0.9' "`
    `"--compressed"

for domain in "${apex_domains[@]}"; do
    for scheme in 'http' 'https'; do
        for subdomain in '' 'www.'; do
           # echo -e         "\n""  ${scheme}://${subdomain}${domain}"
            # echo "  $curl_command  ${scheme}://${subdomain}${domain}"
            eval   "$curl_command  ${scheme}://${subdomain}${domain}" 2>&1 | \
                tr -d '\r' | grep -i --color=always 'Issuer:.*';
        done
    done
done
